
package com.example.congduy.landmonitoring;

import android.support.v7.app.AppCompatActivity;
import com.anychart.chart.common.dataentry.DataEntry;
import com.anychart.chart.common.dataentry.ValueDataEntry;
import java.util.ArrayList;
import java.util.List;

public class LineChartActivity extends AppCompatActivity {

    // ----------------------------------- Node 1 -----------------------------------
    protected List<DataEntry> getListNhietDo1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin1() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 28));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 2 -----------------------------------
    protected List<DataEntry> getListNhietDo2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin2() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 3 -----------------------------------
    protected List<DataEntry> getListNhietDo3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin3() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 4 -----------------------------------
    protected List<DataEntry> getListNhietDo4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin4() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 5 -----------------------------------
    protected List<DataEntry> getListNhietDo5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin5() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 6 -----------------------------------
    protected List<DataEntry> getListNhietDo6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin6() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 7 -----------------------------------
    protected List<DataEntry> getListNhietDo7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin7() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 8 -----------------------------------
    protected List<DataEntry> getListNhietDo8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin8() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 9 -----------------------------------
    protected List<DataEntry> getListNhietDo9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin9() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }


    // ----------------------------------- Node 10 -----------------------------------
    protected List<DataEntry> getListNhietDo10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 23));
        seriesData.add(new ValueDataEntry(2.3, 24));
        seriesData.add(new ValueDataEntry(3.4, 25));
        seriesData.add(new ValueDataEntry(4.5, 26));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDoam10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPH10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListAnhSang10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListDA_Dat10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
    protected List<DataEntry> getListPin10() {
        List<DataEntry> seriesData = new ArrayList<>();
        seriesData.add(new ValueDataEntry(1.2, 28));
        seriesData.add(new ValueDataEntry(2.3, 29));
        seriesData.add(new ValueDataEntry(3.4, 30));
        seriesData.add(new ValueDataEntry(4.5, 30));
        seriesData.add(new ValueDataEntry(5.6, 31));
        seriesData.add(new ValueDataEntry(6.7, 28));
        seriesData.add(new ValueDataEntry(7.8, 29));
        seriesData.add(new ValueDataEntry(8.9, 27));
        seriesData.add(new ValueDataEntry(9.5, 31));
        seriesData.add(new ValueDataEntry(10.5, 30));
        seriesData.add(new ValueDataEntry(12, 32));
        seriesData.add(new ValueDataEntry(13, 28));
        seriesData.add(new ValueDataEntry(14, 32));
        seriesData.add(new ValueDataEntry(15, 28));
        seriesData.add(new ValueDataEntry(16, 32));
        seriesData.add(new ValueDataEntry(17, 28));
        seriesData.add(new ValueDataEntry(18, 32));
        seriesData.add(new ValueDataEntry(19, 28));
        seriesData.add(new ValueDataEntry(19.2, 32));
        seriesData.add(new ValueDataEntry(20, 28));
        seriesData.add(new ValueDataEntry(21, 32));
        seriesData.add(new ValueDataEntry(22, 28));
        seriesData.add(new ValueDataEntry(23, 32));
        seriesData.add(new ValueDataEntry(23.2, 28));
        seriesData.add(new ValueDataEntry(23.3, 32));
        seriesData.add(new ValueDataEntry(23.4, 28));
        return seriesData;
    }
}
